-- =============================================================================
-- Leave Policy Template Seed Data
-- =============================================================================
-- Creates 3 sample leave policy templates with comprehensive entitlements
-- for demonstration and testing purposes.
-- =============================================================================

-- Prerequisites: Requires company_id = 1 and leave types to be already created

-- =============================================================================
-- Template 1: DEFAULT - Default policy for all employees
-- =============================================================================
INSERT INTO leave_policy_templates (
    tenant_id, company_id, code, name, description, leave_year_start,
    criteria, entitlements, effective_from, effective_to, is_active, is_default,
    priority, version, created_by, updated_by
) VALUES (
    'DEFAULT_TENANT',
    1,
    'DEFAULT',
    'Default Leave Policy',
    'Default leave policy template applied to all employees unless a more specific template matches',
    1, -- January
    '{}'::jsonb, -- Empty criteria = applies to all
    '[
        {
            "leaveTypeCode": "CL",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "ANNUAL",
            "annualQuota": 12.0,
            "creditTiming": "YEAR_START",
            "yearEndAction": "CARRY_FORWARD",
            "maxCarryForward": 5.0,
            "carryForwardExpiry": "Q1",
            "encashmentAllowed": false,
            "proRataOnJoining": true,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 5.0,
            "advanceNoticeDays": 0,
            "maxConsecutiveDays": 5,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": false,
            "attachmentRequiredAfterDays": 3,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "SL",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "ANNUAL",
            "annualQuota": 7.0,
            "creditTiming": "YEAR_START",
            "yearEndAction": "LAPSE",
            "maxCarryForward": 0.0,
            "encashmentAllowed": false,
            "proRataOnJoining": true,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 7.0,
            "advanceNoticeDays": 0,
            "maxConsecutiveDays": 7,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": true,
            "attachmentRequiredAfterDays": 2,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "EL",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "MONTHLY",
            "monthlyCredit": 1.25,
            "creditTiming": "MONTH_END",
            "yearEndAction": "CARRY_AND_ENCASH",
            "maxCarryForward": 30.0,
            "carryForwardExpiry": "NEVER",
            "encashmentAllowed": true,
            "maxEncashment": 30.0,
            "proRataOnJoining": true,
            "minDaysPerApplication": 1.0,
            "maxDaysPerApplication": 30.0,
            "advanceNoticeDays": 15,
            "maxConsecutiveDays": 30,
            "allowHalfDay": false,
            "allowHourly": false,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP",
            "encashPayheadCode": "EL_ENCASH"
        },
        {
            "leaveTypeCode": "LOP",
            "isEnabled": true,
            "isPaid": false,
            "creditFrequency": "UNLIMITED",
            "yearEndAction": "NONE",
            "proRataOnJoining": false,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 30.0,
            "advanceNoticeDays": 0,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "LWP",
            "isEnabled": true,
            "isPaid": false,
            "creditFrequency": "UNLIMITED",
            "yearEndAction": "NONE",
            "proRataOnJoining": false,
            "minDaysPerApplication": 1.0,
            "maxDaysPerApplication": 90.0,
            "advanceNoticeDays": 30,
            "allowHalfDay": false,
            "allowHourly": false,
            "requiresAttachment": true,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "COMP-OFF",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "COMPENSATORY",
            "yearEndAction": "LAPSE",
            "proRataOnJoining": false,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 2.0,
            "advanceNoticeDays": 0,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP",
            "compOffExpiryDays": 90,
            "compOffMinHoursFullDay": 8.0,
            "compOffMinHoursHalfDay": 4.0
        },
        {
            "leaveTypeCode": "PERMISSION",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "PERMISSION",
            "yearEndAction": "LAPSE",
            "proRataOnJoining": false,
            "allowHalfDay": false,
            "allowHourly": true,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP",
            "permissionMaxInstancesPerMonth": 3,
            "permissionMaxHoursPerMonth": 6.0,
            "permissionMaxHoursPerInstance": 2.0,
            "permissionLimitType": "WHICHEVER_FIRST",
            "permissionExcessHandling": "CONVERT_TO_LEAVE",
            "permissionExcessRounding": "ROUND_NEAREST_HALF",
            "permissionConversionRate": 8.0,
            "permissionDeductFromLeaveType": "CL",
            "permissionFallbackLeaveType": "LOP"
        }
    ]'::jsonb,
    '2025-01-01',
    NULL, -- No end date
    true,
    true, -- Is default
    0, -- Lowest priority
    1,
    'SYSTEM',
    'SYSTEM'
);

-- =============================================================================
-- Template 2: STAFF - Policy for staff employees
-- =============================================================================
INSERT INTO leave_policy_templates (
    tenant_id, company_id, code, name, description, leave_year_start,
    criteria, entitlements, effective_from, effective_to, is_active, is_default,
    priority, version, created_by, updated_by
) VALUES (
    'DEFAULT_TENANT',
    1,
    'STAFF',
    'Staff Leave Policy',
    'Leave policy template for staff employees with enhanced CL and SL quotas',
    1, -- January
    '{"classifications": ["STAFF"]}'::jsonb,
    '[
        {
            "leaveTypeCode": "CL",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "ANNUAL",
            "annualQuota": 15.0,
            "creditTiming": "YEAR_START",
            "yearEndAction": "CARRY_FORWARD",
            "maxCarryForward": 8.0,
            "carryForwardExpiry": "Q1",
            "encashmentAllowed": false,
            "proRataOnJoining": true,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 5.0,
            "advanceNoticeDays": 0,
            "maxConsecutiveDays": 5,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": false,
            "attachmentRequiredAfterDays": 3,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "SL",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "ANNUAL",
            "annualQuota": 10.0,
            "creditTiming": "YEAR_START",
            "yearEndAction": "LAPSE",
            "maxCarryForward": 0.0,
            "encashmentAllowed": false,
            "proRataOnJoining": true,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 10.0,
            "advanceNoticeDays": 0,
            "maxConsecutiveDays": 10,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": true,
            "attachmentRequiredAfterDays": 2,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "EL",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "MONTHLY",
            "monthlyCredit": 1.25,
            "creditTiming": "MONTH_END",
            "yearEndAction": "CARRY_AND_ENCASH",
            "maxCarryForward": 30.0,
            "carryForwardExpiry": "NEVER",
            "encashmentAllowed": true,
            "maxEncashment": 30.0,
            "proRataOnJoining": true,
            "minDaysPerApplication": 1.0,
            "maxDaysPerApplication": 30.0,
            "advanceNoticeDays": 15,
            "maxConsecutiveDays": 30,
            "allowHalfDay": false,
            "allowHourly": false,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP",
            "encashPayheadCode": "EL_ENCASH"
        },
        {
            "leaveTypeCode": "LOP",
            "isEnabled": true,
            "isPaid": false,
            "creditFrequency": "UNLIMITED",
            "yearEndAction": "NONE",
            "proRataOnJoining": false,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 30.0,
            "advanceNoticeDays": 0,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "LWP",
            "isEnabled": true,
            "isPaid": false,
            "creditFrequency": "UNLIMITED",
            "yearEndAction": "NONE",
            "proRataOnJoining": false,
            "minDaysPerApplication": 1.0,
            "maxDaysPerApplication": 90.0,
            "advanceNoticeDays": 30,
            "allowHalfDay": false,
            "allowHourly": false,
            "requiresAttachment": true,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "COMP-OFF",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "COMPENSATORY",
            "yearEndAction": "LAPSE",
            "proRataOnJoining": false,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 2.0,
            "advanceNoticeDays": 0,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP",
            "compOffExpiryDays": 90,
            "compOffMinHoursFullDay": 8.0,
            "compOffMinHoursHalfDay": 4.0
        },
        {
            "leaveTypeCode": "PERMISSION",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "PERMISSION",
            "yearEndAction": "LAPSE",
            "proRataOnJoining": false,
            "allowHalfDay": false,
            "allowHourly": true,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP",
            "permissionMaxInstancesPerMonth": 4,
            "permissionMaxHoursPerMonth": 8.0,
            "permissionMaxHoursPerInstance": 2.0,
            "permissionLimitType": "WHICHEVER_FIRST",
            "permissionExcessHandling": "CONVERT_TO_LEAVE",
            "permissionExcessRounding": "ROUND_NEAREST_HALF",
            "permissionConversionRate": 8.0,
            "permissionDeductFromLeaveType": "CL",
            "permissionFallbackLeaveType": "LOP"
        }
    ]'::jsonb,
    '2025-01-01',
    NULL,
    true,
    false,
    50, -- Higher priority than default
    1,
    'SYSTEM',
    'SYSTEM'
);

-- =============================================================================
-- Template 3: MANAGER - Policy for managers with premium benefits
-- =============================================================================
INSERT INTO leave_policy_templates (
    tenant_id, company_id, code, name, description, leave_year_start,
    criteria, entitlements, effective_from, effective_to, is_active, is_default,
    priority, version, created_by, updated_by
) VALUES (
    'DEFAULT_TENANT',
    1,
    'MANAGER',
    'Manager Leave Policy',
    'Premium leave policy template for managers with highest quotas and flexibility',
    1, -- January
    '{"designations": ["MANAGER"]}'::jsonb,
    '[
        {
            "leaveTypeCode": "CL",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "ANNUAL",
            "annualQuota": 18.0,
            "creditTiming": "YEAR_START",
            "yearEndAction": "CARRY_FORWARD",
            "maxCarryForward": 10.0,
            "carryForwardExpiry": "Q2",
            "encashmentAllowed": true,
            "maxEncashment": 5.0,
            "proRataOnJoining": true,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 10.0,
            "advanceNoticeDays": 0,
            "maxConsecutiveDays": 10,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": false,
            "attachmentRequiredAfterDays": 5,
            "lopPayheadCode": "LOP",
            "encashPayheadCode": "CL_ENCASH"
        },
        {
            "leaveTypeCode": "SL",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "ANNUAL",
            "annualQuota": 12.0,
            "creditTiming": "YEAR_START",
            "yearEndAction": "CARRY_FORWARD",
            "maxCarryForward": 3.0,
            "carryForwardExpiry": "Q1",
            "encashmentAllowed": false,
            "proRataOnJoining": true,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 12.0,
            "advanceNoticeDays": 0,
            "maxConsecutiveDays": 12,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": true,
            "attachmentRequiredAfterDays": 3,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "EL",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "MONTHLY",
            "monthlyCredit": 1.5,
            "creditTiming": "MONTH_END",
            "yearEndAction": "CARRY_AND_ENCASH",
            "maxCarryForward": 45.0,
            "carryForwardExpiry": "NEVER",
            "encashmentAllowed": true,
            "maxEncashment": 45.0,
            "proRataOnJoining": true,
            "minDaysPerApplication": 1.0,
            "maxDaysPerApplication": 45.0,
            "advanceNoticeDays": 7,
            "maxConsecutiveDays": 45,
            "allowHalfDay": false,
            "allowHourly": false,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP",
            "encashPayheadCode": "EL_ENCASH"
        },
        {
            "leaveTypeCode": "LOP",
            "isEnabled": true,
            "isPaid": false,
            "creditFrequency": "UNLIMITED",
            "yearEndAction": "NONE",
            "proRataOnJoining": false,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 30.0,
            "advanceNoticeDays": 0,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "LWP",
            "isEnabled": true,
            "isPaid": false,
            "creditFrequency": "UNLIMITED",
            "yearEndAction": "NONE",
            "proRataOnJoining": false,
            "minDaysPerApplication": 1.0,
            "maxDaysPerApplication": 180.0,
            "advanceNoticeDays": 15,
            "allowHalfDay": false,
            "allowHourly": false,
            "requiresAttachment": true,
            "lopPayheadCode": "LOP"
        },
        {
            "leaveTypeCode": "COMP-OFF",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "COMPENSATORY",
            "yearEndAction": "CARRY_FORWARD",
            "maxCarryForward": 5.0,
            "carryForwardExpiry": "YEAR_END",
            "proRataOnJoining": false,
            "minDaysPerApplication": 0.5,
            "maxDaysPerApplication": 3.0,
            "advanceNoticeDays": 0,
            "allowHalfDay": true,
            "allowHourly": false,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP",
            "compOffExpiryDays": 180,
            "compOffMinHoursFullDay": 8.0,
            "compOffMinHoursHalfDay": 4.0
        },
        {
            "leaveTypeCode": "PERMISSION",
            "isEnabled": true,
            "isPaid": true,
            "creditFrequency": "PERMISSION",
            "yearEndAction": "LAPSE",
            "proRataOnJoining": false,
            "allowHalfDay": false,
            "allowHourly": true,
            "requiresAttachment": false,
            "lopPayheadCode": "LOP",
            "permissionMaxInstancesPerMonth": 6,
            "permissionMaxHoursPerMonth": 12.0,
            "permissionMaxHoursPerInstance": 3.0,
            "permissionLimitType": "WHICHEVER_FIRST",
            "permissionExcessHandling": "LAPSE",
            "permissionExcessRounding": "ROUND_NEAREST_HALF",
            "permissionConversionRate": 8.0,
            "permissionDeductFromLeaveType": "CL",
            "permissionFallbackLeaveType": "LOP"
        }
    ]'::jsonb,
    '2025-01-01',
    NULL,
    true,
    false,
    100, -- Highest priority
    1,
    'SYSTEM',
    'SYSTEM'
);

-- =============================================================================
-- Verification Queries
-- =============================================================================
-- SELECT * FROM leave_policy_templates WHERE tenant_id = 'DEFAULT_TENANT';
-- SELECT code, name, is_default, priority, jsonb_array_length(entitlements) as entitlement_count FROM leave_policy_templates WHERE tenant_id = 'DEFAULT_TENANT';
